name: Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: empresa_test

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: empresa_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      # Cria as tabelas no banco de testes
      - run: npx sequelize-cli db:migrate --env test

      # Executa os testes1

      - run: npm run build