name: Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: empresa

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: empresa
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Verificar MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -p"$DB_PASSWORD" --silent; do
            echo "Aguardando MySQL..."
            sleep 2
          done

      - run: npm install

      - run: npm run build